import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { Pacifico, Borel } from "next/font/google";

const borel = Borel({
  subsets: ['latin'],
  variable: '--font-borel',
  weight: '400',
  display: 'swap',
});

const pacifico = Pacifico({
  subsets: ['latin'],
  variable: '--font-pacifico',
  weight: '400',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${borel.variable} antialiased bg-gray-100`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}

